[package]
name = "july-cli"
version = "0.1.0"

[dependencies]
july-common = { path = "../common" }
vosk-sys = "0.1"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
cpal = "0.14.0"